print('Ciao programmatore benvenuto nel tuo primo programma in Python! Come ti chiami?')
nome=input()
print(nome+' ... e vuoi imparare a usare Python? Ottima scelta')
età=input('Quanti anni hai?')
print(età+' anni. Bene, il giorno in cui ne compirai ' + str(int(età) + 1) + ' ti farò gli auguri')